$Configs = $HOME/.config/hypr/Configs   # Configs directory path


source= $Configs/Startup_Apps.conf

source= $Configs/ENVariables.conf

source= $Configs/WindowRules.conf

source= $Configs/Decorations.conf

source= $Configs/Animations.conf

source= $Configs/Keybinds.conf

source= $Configs/Settings.conf          # Hyprland Settings.

