# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0E0000)
$foreground = rgb(F1DDE0)
$color0 = rgb(110000)
$color1 = rgb(713223)
$color2 = rgb(662C77)
$color3 = rgb(9D4A29)
$color4 = rgb(90368C)
$color5 = rgb(B25F23)
$color6 = rgb(A13C48)
$color7 = rgb(E3C7CA)
$color8 = rgb(9F8B8D)
$color9 = rgb(833825)
$color10 = rgb(76318C)
$color11 = rgb(B24820)
$color12 = rgb(9F319A)
$color13 = rgb(ED7E2F)
$color14 = rgb(D75060)
$color15 = rgb(E3C7CA)
