[mgr]
show_hidden = true
linemode = "btime"
show_symlink = true

[preview]
image_delay=100

[opener]
edit = [
	{ run = 'nvim "$1"', desc = "Neo Vim", block = true, for = "unix"},
	{ run = 'nano "$1"', desc = "Nano", block = true, for = "unix" },
]

open = [
	{ run = 'imv "$1"', desc = "Imv", block = false, for = "unix"},
]

play = [
	{ run = 'ffplay -volume 30 -x 800 -y 400 -seek_interval 5 "$1"', desc = "FFPlay", block = true, for = "unix"},
]

[open]
rules = [
	{ name = "*/", use = [ "reveal" ] },

	{ mime = "text/*", use = [ "edit", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal" ] },
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
]
