$vol = pamixer --get-volume
$browser = prime-run firefox
$fileManager = kitty -e fish -c 'y'
$menu = rofi -show drun
$edit_config_menu = ~/.config/rofi/scripts/favorite_paths.rasi
$change_wallpaper = ~/.config/rofi/scripts/wallpaper_changer.rasi
$term = kitty
