windowrule {
  name = windowrule-100
  match:class = ^(VSCode|code-oss|code-url-handler)$
  opacity = 0.9 0.7
  workspace = 3
  float = on
  center = on
  size = 1600 1000
}

windowrule {
  name = windowrule-200
  match:class = ^(org.telegram.desktop|discord)$
  workspace = 4
  opacity = 0.95 0.7
}

windowrule {
  name = windowrule-300
  match:class = ^(Spotify)$
  workspace = 5
  opacity = 0.95 0.7
}

windowrule {
  name = windowrule-400
  match:class = ^(VirtualBox Manager)$
  workspace = 7
}

windowrule {
  name = windowrule-401
  match:initial_class = ^(VirtualBox Machine)$
  workspace = 7
  float = on
  center = on
  size = (monitor_w*0.8) (monitor_h*0.9)
}

windowrule {
  name = windowrule-600
  match:class = ^(firefox|google-chrome)$
  workspace = 2
  opacity = 0.98 0.7
  fullscreen = on
}

windowrule {
  name = windowrule-700
  match:class = ^(kitty)$
  workspace = 1
  opacity = 0.95 0.7
  size = (monitor_w*0.8) (monitor_h*0.8)
  float = on
}

windowrule {
  name = windowrule-800
  workspace = 10
  fullscreen = on
  opacity = 0.98 0.8
  match:class = ^(obsidian)$
}

windowrule {
  name = windowrule-900
  match:title = ^(Welcome to PyCharm)$
  workspace = 1
  float = on
  center = on
  size = (monitor_w*0.5) (monitor_h*0.6)
  opacity = 0.95 0.7
}

windowrule {
  name = windowrule-901
  match:class = ^(jetbrains-.+)$ # JetBrains IDEs
  workspace = 1
  opacity = 0.95 0.7
}

windowrule {
  name = windowrule-1100
  match:class = ^(cutefish-calculator)$
  move = (monitor_w*0.7) (monitor_h*0.07)
  size = (monitor_w*0.25) (monitor_h*0.7)
  float = on
  opacity = 0.9 0.5
  pin = 1
}

windowrule {
  name = windowrule-1200
  match:class = ^(nm-applet|nm-connection-editor|blueman-manager|pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$
  opacity = 0.9 0.7
  size = (monitor_w*0.6) (monitor_h*.6)
  float = on
  center = on
  pin = 1
}

windowrule {
  name = windowrule-1201
  match:class = ^(lxqt-policykit-agent)$
  opacity = 0.9 0.7
  size = (monitor_w*0.3) (monitor_h*0.3)
  float = on
  center = on
}
